# Generated by Django 3.0 on 2022-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('birthday', models.CharField(blank=True, max_length=200)),
                ('age', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=200)),
                ('programm', models.CharField(blank=True, max_length=200)),
                ('campus', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=200)),
                ('mail', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('vk', models.CharField(blank=True, max_length=200)),
                ('ready_or_not', models.CharField(blank=True, max_length=200)),
                ('question_1', models.TextField(blank=True)),
                ('question_2', models.TextField(blank=True)),
                ('question_3', models.TextField(blank=True)),
                ('question_4', models.TextField(blank=True)),
                ('question_5', models.TextField(blank=True)),
                ('question_6', models.TextField(blank=True)),
                ('question_7', models.TextField(blank=True)),
                ('question_8', models.TextField(blank=True)),
                ('question_9', models.TextField(blank=True)),
                ('question_10', models.TextField(blank=True)),
                ('question_11', models.TextField(blank=True)),
                ('question_12', models.TextField(blank=True)),
                ('question_13', models.TextField(blank=True)),
                ('question_14', models.TextField(blank=True)),
                ('question_15', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('size', models.CharField(blank=True, max_length=200)),
                ('checkbox', models.BooleanField(blank=True)),
            ],
        ),
    ]
